### ISSUE TITLE
Notifications need to start with the application supervisor

### ISSUE THREAD

**Issue by olafura** [tompave/fun_with_flags#31] opened 2018-07-10 21:03 UTC
The Notification module has to wait on the Application that contains the PubSub to start otherwise it fails, now this is handled with retries but they break really easily and littler tests.

I know that the notifications are now optional but I think the right approach is just to have the Application supervisor that spawns the PubSub also spawn the the Notification module.

Here are the errors: 

```
FunWithFlags: Cannot subscribe to Phoenix.PubSub process MyApp.PubSub (exception: %ArgumentError{message: "argument error"})
FunWithFlags: retrying to subscribe to Phoenix.PubSub, attempt 2
```

**Comment by tompave** [comment] 2018-07-10 21:14
Hi, thanks for the report.
Do you have any reproduction steps?

**Comment by tompave** [comment] 2018-07-10 21:15
Also, would you say it's related to https://github.com/tompave/fun_with_flags/issues/27 ?

**Comment by olafura** [comment] 2018-07-10 21:32
I believe it's related to #27. That one causes a crash but the underlying reason that the application hasn't started yet and then Phoenix.PubSub doesn't know about the subscription source.
Here I have dummy repo
https://github.com/olafura/fun_with_flag_notification_bug
You just need to do ```
mix deps.get
iex -S mix
```
And you'll see it.

**Comment by tompave** [comment] 2020-02-09 23:36
Closing as it's an old issue.

**Comment by olafura** [comment] 2020-05-19 09:03
@tompave This is still a problem

**Comment by scottmessinger** [comment] 2020-08-29 00:51
This is happening to us as well

**Comment by mustela** [comment] 2020-10-14 08:48
Any clue or workaround for this issue? Still happening :/

**Comment by tompave** [comment] 2020-11-14 22:52
Hi @olafura, in that example repo, can you please point out what is causing the issue? At the moment I see that the initial commit does everything: create the new Mix+Phoenix project, and fun_with_flags. I'm not sure if it configures anything else or not, but in order to verify it I'd have to `diff` it against another brand new Phoenix project.

It would be helpful if you could separate the "new app" commit from the "add fun_with_flags" commit, and then any "this config causes the issues" commit, if present.

**Comment by mindreader** [comment] 2021-03-03 15:01
This also happens to us.  It happens because the startup time of our app is very long, but fun with flags starts up instantly.  Therefore the pubsub within fwf tries six times, gives up, throws a nasty error, gets restarted by the supervisor and does it a couple more times before the application has finished starting up at which point it succeeds.

I have submitted a pr, but I think it needs more work to survive the test suite.

**Comment by tompave** [comment] 2021-03-03 22:00
I've had a look at the PR. Thank you @mindreader, but I am not convinced that's an approach I can accept for the package.

I can think of two solutions to this issue:
1. Provide an option to not start FunWithFlags as its own application, and also provide an API to obtain a [child spec](https://hexdocs.pm/elixir/Supervisor.html#t:child_spec/0) (with `type: :supervisor`) so that host applications can manually put it in their Phoenix supervision trees.
2. Improve the [subscribe function and its failure logic](https://github.com/tompave/fun_with_flags/blob/4b4c0ea5a3dd52fabeee93a8dc309425d5ef0414/lib/fun_with_flags/notifications/phoenix_pubsub.ex#L63) to not fail this way. Maybe we can test that the pubsub process is alive a few times before even trying to subscribe.

I think that `2` would be fairly easy, but `1` is possibly more useful also for other use cases.

**Comment by tompave** [comment] 2021-03-03 22:12
More thoughts on `1`. I imagine that the interface would have two parts.

1. Tell FWF to not start as its own application:

```elixir
# An application's config file.
use Config
config :fun_with_flags, start_application: false
```

2. Put it in the host application's supervision tree:

```diff
  def start(_type, _args) do
    children = [
      HelloWorld.Repo,
      HelloWorldWeb.Telemetry,
      {Phoenix.PubSub, name: HelloWorld.PubSub},
      HelloWorldWeb.Endpoint
+     FunWithFlags.Supervisor
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: HelloWorld.Supervisor]
    Supervisor.start_link(children, opts)
  end
```

Where `FunWithFlags.Supervisor` implements [`child_spec/0`](https://hexdocs.pm/elixir/Supervisor.html#t:child_spec/0).

**Comment by scottmessinger** [comment] 2021-03-03 22:24
@tompave I really like that idea!

**Comment by mindreader** [comment] 2021-03-03 22:41
I like both of those ideas.  I will attempt to make a PR for one of them (probably the first) when I have a bit of time.

**Comment by tompave** [comment] 2021-03-04 01:24
Awesome, thanks!

**Comment by tompave** [comment] 2021-03-11 23:50
I've started to look into this. I have a draft to extract the supervision tree into a reusable module: https://github.com/tompave/fun_with_flags/pull/103

Telling the package to not automatically start the app seems to be a bit difficult though. You can follow the progress on this, and contribute suggestions, here: https://elixirforum.com/t/mix-project-how-to-control-whether-the-application-is-started-based-on-config/38124

**Comment by tompave** [comment] 2021-03-14 01:57
Ok, I think I've found a reasonable solution: https://github.com/tompave/fun_with_flags/pull/103. It's not quite what I proposed above, but it's close. Since this can't be accomplished with the config API, application auto-start must be disabled in the Mixfile.

@olafura @scottmessinger @mindreader @mustela, if you could try that branch and let me know if it works, that would be appreciated.

**Comment by tompave** [comment] 2021-03-22 21:31
The PR 👆 that addresses this has landed on master. I'll close this issue once I've released a new version that includes the fix. For now, master should be stable enough to be used.

**Comment by tompave** [comment] 2021-11-15 02:09
That change has been released.

**Closed by tompave** 2021-11-15 02:09 UTC
