### ISSUE TITLE
Persistence config not recognized in release

### ISSUE THREAD

**Issue by A-Legg** [tompave/fun_with_flags#109] opened 2021-06-28 21:31 UTC
# Versions 
erlang 23.1
elixir 1.11.3-otp-23
fun_with_flags 1.6.0

# Problem 

When running our application in a production release FWF doesn't seem to be accessing our configs/persistence adapter and is raising an exception when trying to call `FunWithFlags.all_flags()`.

Config: 

```
config :fun_with_flags, :persistence,
  adapter: FunWithFlags.Store.Persistent.Ecto,
  repo: MyApp.Repo
```

Exception raised when visiting the `/feature-flags/flags` endpoints of the UI: 

```
function FunWithFlags.Store.Persistent.Redis.all_flags/0 is undefined (module FunWithFlags.Store.Persistent.Redis is not available)
```

The application runs without issues in the local `dev` environment. I see in [1.5.1](https://github.com/tompave/fun_with_flags/blob/master/CHANGELOG.md#v151) there were some related changes and that there is an open [issue](https://github.com/tompave/fun_with_flags/issues/106) related to running the app in a production release but I haven't been able to identify the cause, any insight would be greatly appreciated.

Thanks!

**Comment by A-Legg** [comment] 2021-06-28 23:34
I see now this is most likely the cause, will have to play around with the new Supervisor functionality that hasn't been released yet to verify in the morning.  

>For example, if you have configured the Phoenix.PubSub cache-busting notification adapter, one of FunWithFlag's processes will immediately try to subscribe to its notifications channel using the provided PubSub process identifier. If that process is not available, FunWithFlags will retry a few times and then give up and raise an exception.

**Comment by A-Legg** [comment] 2021-06-29 21:15
Updated to the latest commit and added the Supervisor to our application's tree and are seeing the same error.

**Comment by A-Legg** [comment] 2021-06-29 23:15
So it looks like this is the call stack to get all flags: 

```
FunWithFlags.all\_flags -> delegates to FunWithFlags.Store.all -> calls imported FunWithFlags.Config.persistence\_adapter()
```

It looks like the imported call to fetch the persistence adapter in the `FunWithFlags.Store` is returning the default Redis value, however, when we call the function in the `Config` module directly from the remote console it returns to correct Ecto value....

**Comment by durub** [comment] 2021-07-13 19:51
I'm having the same issue on Elixir 1.12 with Erlang/OTP 23. It works fine in `iex` but visiting `/feature-flags/flags` from the UI raises this exception.

Did you find a solution, @A-Legg?

**Comment by A-Legg** [comment] 2021-07-13 19:55
>Did you find a solution, @A-Legg?

While we didn't test the solution in a release we suspect that removing the `delegates` and `imports` that I mention above and simply calling the appropriate function at runtime would resolve it. Our use case was quite simple so we decided to just roll our own for the time being and moved on.

**Comment by durub** [comment] 2021-07-13 20:05
Thanks for the update! I was tempted to roll my own, but FWF seems like a well-thought-out library.

I was having this problem on my local machine, so I:

1. Deleted `deps` and `_build` folders
2. `mix deps.get`
3. `mix deps.compile`
4. `mix phx.server`

And, strangely, it works now. Hoping it won't break in production, but with my current setup, I don't think it will. My issue seems different than yours, even though it is the same error.

Maybe yours has something to do with [this common issue](https://github.com/tompave/fun_with_flags#configuration-changes-have-no-effect-in-mix_envdev) and releases. However, with a quick research, it seems that this should not be a problem in recent releases. Weird...

Thanks for the prompt reply and help, @A-Legg! Have a nice week!

**Comment by connorlay** [comment] 2021-07-16 18:39
Glad I found this thread! I'm adding FunWithFlags to a new project and ran into the same issue when running my application as a release. I opened a PR fixing for this issue here: https://github.com/tompave/fun_with_flags/pull/111

**Comment by adamz-prescribefit** [comment] 2021-08-18 20:53
Found a temporary workaround for this issue until the PR is merged, at least for people doing docker deploys. Do the same thing as with local issues after running `deps.get` and `deps.compile` and before the `mix compile`:
```
RUN rm -r _build/prod/lib/fun_with_flags
RUN rm -r _build/prod/lib/pace
```

**Comment by dvic** [comment] 2021-09-15 14:03
We were also bitten by this in production. In our case we "optimized" the docker build by running `mix deps.compile` *before* copying over the config files. A "solution" that keeps the config at compile time but avoids this confusing situation would be to use `Application.compile_env` instead of `Application.get_env`.

I just checked and it works, if you compile the app while changing the value you get this compile error:

```
ERROR! the application :fun_with_flags has a different value set for key :persistence during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was set to: [adapter: FunWithFlags.Store.Persistent.Ecto, repo: My.Repo]
  * Runtime value was set to: [adapter: FunWithFlags.Store.Persistent.Redis, repo: My.Repo]

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile fun_with_flags --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag
  *
```

@tompave what do you think? If there is interest in such a solution I can create a PR.

**Comment by dvic** [comment] 2021-09-15 14:06
@A-Legg See above, are the config files in your build present *before* or *after* you run `mix deps.compile`?

**Comment by tompave** [comment] 2021-11-15 02:11
Hello, thank you for reporting the issue and for researching the problem.
I've been away from this project for some time, but I'll have a look soon.

**Comment by tompave** [comment] 2021-11-15 21:37
Ok, I've caught up with the issue.

This is very likely caused by the persistence adapter (Ecto or Redis) being stored in a module attribute at compile time, based on the configuration _available at compile time_. As @durub mentioned above, this is explained [in the readme](https://github.com/tompave/fun_with_flags#common-issues), with reference to the local env.

With regard to what @dvic described, this problem will appear if your Docker file first copies over the deps without config, then compiles them, and _then_ copies over the config files.

With regard to the situation described by @A-Legg in the opening message, I'm not sure about the exact circumstances or how the release was built, bit it sounds like the same thing.

The suggestion to use [`Application.compile_env/3`](https://hexdocs.pm/elixir/1.12.3/Application.html#compile_env/3) is something I considered in the past to address the problem. Unfortunately, since that function first appeared in Elixir 1.10, I can't adopt it and still keep backward compatibility with older Elixirs. The good news is that FWF v1.7.0 (released yesterday) bumps the supported range to Elixir 1.9-1.12 (and drops 1.8), and FWF v1.8.0 will bump the supported range to Elixir 1.10-1.13, which means that I'll be able to update the config to use that new helper.

**Comment by tompave** [comment] 2021-11-15 21:52
Looks like this was closed automatically when I merged the PR.
I'm reopening it to track if the merged PR will solve the problem for the people who reported it. Please try to use the latest `master` and let me know.

**Comment by tompave** [comment] 2021-11-16 23:48
@dvic I've adopted `Application.compile_env/3` in https://github.com/tompave/fun_with_flags/pull/116.

**Closed** 2021-12-06 10:00 UTC

**Comment by aseigo** [comment] 2022-12-09 13:05
I can confirm that this still  happens after a fresh install of `fun_with_flags` (fun_with_flags 1.10.1, elixir 1.13.0, and erlang 24.1.7). I added the configuration to the config file and then compiled, and got the dreaded 'ERROR! the application :fun_with_flags has a different value set for key :persistence during runtime compared to compile time.' error; I had to do `mix deps.compile fun_with_flags --force` to get it to work. Is #116 only expected to work in versions of elixir later than 1.13.0?

**Comment by tompave** [comment] 2023-01-04 01:56
Hi @aseigo, that's now the expected behaviour. From the [Elixir 1.10 changelog](https://github.com/elixir-lang/elixir/blob/v1.10/CHANGELOG.md#tracking-of-compile-time-configuration):

> By using `compile_env/3`, Elixir will store the values used during compilation and compare them with the runtime values whenever your system starts, raising an error in case they differ. This helps developers ensure they are running their production systems with the configuration they intend to.

This is better than the exception that was raised in FWF before, as is reported in the [opening message](https://github.com/tompave/fun_with_flags/issues/109#issue-932011817) of this issue:

> ```
> function FunWithFlags.Store.Persistent.Redis.all_flags/0 is undefined (module FunWithFlags.Store.Persistent.Redis is not available)
> ```

That exception was not very informative, whereas the error you're now getting from `compile_env/3` is very clear.

Unfortunately, FWF relies on compile time config, and there isn't a safe and automatic way to deal with compile-time config mismatch at runtime, because it could be a genuine mistake. The best solution is to tell the developer what the error is.

If you still think that something is wrong, please open another issue and provide some reproduction steps. I'm afraid that from your message I can't easily understand the sequence of things you're doing.
