### ISSUE TITLE
Should we be compiling in configs

### ISSUE THREAD

**Issue by olafura** [tompave/fun_with_flags#14] opened 2017-12-13 15:49 UTC
This line means that umbrella apps won't work unless they have the application where the config was initially defined as a dependency:
https://github.com/tompave/fun_with_flags/blob/3aa0d11cd050e9690d7b4d551674355f6dbcd03d/lib/fun_with_flags/store/persistent/ecto.ex#L12

**Comment by tompave** [comment] 2017-12-13 16:55
Hi, thank you for flagging the issue.

I'm not sure I follow, sorry. I'm not too familiar with umbrella apps, and I've never tries to use this package in an umbrella app.

Some issues with those module attributes are mentioned [in the readme](https://github.com/tompave/fun_with_flags#configuration-changes-have-no-effect-in-mix_envdev), but it seems that you're reporting something different.

Can you please add more details? If you can propose a solution that keeps the tests green, I'd be happy to consider it.

**Comment by olafura** [comment] 2017-12-13 16:58
Hope the PR explains the problem better than my description in the issue above ;)

**Comment by tompave** [comment] 2017-12-13 16:59
Regarding the title question:

> Should we be compiling in configs?

I initially did it because I didn't want the performance bottleneck of reading those values from an ETS table all the time, where they would end up if they were simply read dynamically from Mix config.
I guess it's acceptable for things that are not read very often (the Ecto repo is a good example), but I'm not sure about this, for example:
https://github.com/tompave/fun_with_flags/blob/master/lib/fun_with_flags.ex#L30

**Comment by olafura** [comment] 2017-12-13 17:07
@tompave sure I trust your call, have you benchmarked this ETS are usually really performant? If it's really a problem there are some macro possibilities which would allow you to recompile on change.

**Comment by olafura** [comment] 2017-12-13 18:19
@tompave I'm not seeing any difference with `:timer.tc(FunWithFlags, :all_flag_names, [])` between master and the PR. You just tell me if you me to revert any changes in the PR, it's pretty easy todo.

**Comment by tompave** [comment] 2017-12-13 18:28
I've done some synthetic benchmarks, but they might not be too relevant. Rather than speed, I was mainly concerned with the number of inter-process messages and copying data between processes, as that's what happens when you read from an ETS table.

I've been meaning to revisit those decisions though. I considered [fastglobal](https://hex.pm/packages/fastglobal), but now I realize that it would have the same issue that you reported here.

**Comment by tompave** [comment] 2017-12-13 18:37
> I'm not seeing any difference with :timer.tc(FunWithFlags, :all_flag_names, []) between master and the PR. You just tell me if you me to revert any changes in the PR, it's pretty easy todo.

Sorry, I missed this message. Cool, I need to check too. Please leave the PR open.

**Comment by olafura** [comment] 2017-12-13 20:50
Now I'm getting `relation "fun_with_flags_toggles" does not exist` unless I do `mix deps.compile` in the app and then it ruins it for the other apps I'll get to the bottom of this ;)

**Comment by olafura** [comment] 2017-12-14 00:06
I forgot about the step of creating the tables it's been so long :D

**Comment by tompave** [comment] 2017-12-16 11:18
Hi, I was thinking that running two copies of FunWithFlags in a umbrella, each as a dependency of a different OTP application, would be tricky for other reasons.
For example, do you want both copies to read from the same persistent store? (either Ecto or Redis)

**Comment by tompave** [comment] 2017-12-16 11:18
I still mean to do something about this issue, I plan to have a deeper look soon.

**Comment by olafura** [comment] 2017-12-17 01:30
We already have different ecto databases, but yes I think in the general case you want a common database. There are also problem that we were having with new code using FunWithFlags in our existing app that wouldn't compile on prod with out these changes since it couldn't find the repo in the application since it hadn't been compiled yet. I think there are going to be many corner cases, of the attributes.

I really like using attributes to compile in code, especially csv and other data that needs to be parsed once.

The problem is that without these kinds of changes I'm not even sure we could do a migration to a common app which would hold the database for both applications in the umbrella.

**Comment by tompave** [comment] 2018-01-04 10:16
Hey, hi, I've had another look at this.

I was wondering how exactly you are trying to use two "copies" of FunWithFlags in an umbrella application. The API uses global functions by design, so you'd still have to do `FunWithFlags.enabled?(:something)`, with no way to select one of the two. The Mix config is also shared in the umbrella: all the configuration values end up in the `ac_tab` ETS table, where they're grouped by application name (`fun_with_flags`, in this case). In other words, even if we looked up all the configuration dynamically, I see no easy way to run two independent copies of this library in the same umbrella.

The only way I can think of to achieve what you're after is to change the API to accept a context "thing" to be passed as an argument. This context could be a module implementing a behaviour (for example like an Ecto Repo, with mix config values grouped _by repo module name_ if you have multiple repos), or some struct (containing all the required config), or a pid or reference to a process holding the required info. With this, then the API could be:

```elixir
FunWithFlags.enabled?(context_a, :feature_name)
FunWithFlags.enabled?(context_b, :another_feature_name)
```

However, I deliberately stayed away from that approach for a few reasons. The "module with behaviour" one seems the most reasonable, but it also requires a bit of extra set up. It's something that could be adopted in a 2.0 release (if I ever get there), but for the moment it would require a significant change.

Apologies if I'm missing something obvious and there is a simpler solution I'm not seeing! 😅

All of this clearly means that this library is not really designed or intended to be used multiple times in the same application or umbrella. The design I would reach for is to have a separate app inside the umbrella to handle this kind of shared responsibilities. I understand, however, that you seem to have two full-fledged phoenix apps in your umbrella, each with its own ecto repo and DB. I'm afraid that yours is a use case that is not really covered at the moment :-(

> There are also problem that we were having with new code using FunWithFlags in our existing app that wouldn't compile on prod with out these changes since it couldn't find the repo in the application since it hadn't been compiled yet.

I see. Can't you resolve that with a `require`?

**Comment by olafura** [comment] 2018-01-05 00:47
It is a problem, I'll just have to mull on if there is good solution. One solution would be giving people a warning if they hit this issue.

**Comment by tompave** [comment] 2018-01-05 09:00
Yes, adding something to the readme is definitely a good idea.

**Comment by tompave** [comment] 2020-11-18 22:07
All instances of package config compiled in as module attributes have been removed. There is one exception, the `@store` module, because that's meant to be on the hot-path and going through ETS for that would be a performance hit. The rest is gone though

I'm closing this issue. If there is more to discuss about running FWF in an umbrella application, I suggest to open a new issue.

**Closed by tompave** 2020-11-18 22:07 UTC
